# .github/workflows/greetings.yml
name: Greet New Contributors

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # The action automatically looks for .github/greetings.yml
